name: movement_analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip>=22.0.4
  - numpy>=1.23.0
  - pandas>=1.5.0
  - matplotlib>=3.6.0
  - scikit-learn>=1.1.0
  - pyyaml>=6.0
  - scipy>=1.9.0
  - opencv>=4.6.0
  - tqdm>=4.64.0
  - seaborn>=0.12.0
  - joblib>=1.2.0
  - pytest>=7.0.0
  - notebook>=6.4.0
  - pip:
    - mediapipe>=0.9.0
    - plotly>=5.10.0
    - xgboost>=1.6.0
    - black>=22.8.0
    - flake8>=5.0.0
    - av>=9.0.0  # PyAV for advanced video processing