# Default configuration for Movement Analysis System

# Path settings
paths:
  data:
    raw: "data/raw/"
    landmarks: "data/landmarks/"
    features: "data/features/"
    processed_videos:
      basic: "data/processed_videos/basic/"
      annotated: "data/processed_videos/annotated/"
    metadata: "data/metadata/"

# Pose estimation settings
pose_estimation:
  algorithm: "mediapipe"  # Default pose estimator
  mediapipe:
    model_complexity: 2  # 0, 1, or 2
    min_detection_confidence: 0.5
    min_tracking_confidence: 0.5
    static_image_mode: false

# Feature extraction settings
feature_extraction:
  default_movement: "squat"
  preprocess:
    smoothing: true
    smoothing_window: 5
    interpolate_missing: true

# ML model settings
ml_model:
  algorithm: "random_forest"
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42

# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  save_to_file: true
  log_file: "logs/movement_analysis.log"