# Default configuration for Movement Analysis System

# Path settings
paths:
  config:
    movements: "config/movements/"
  data:
    raw: "data/raw/"
    landmarks: "data/landmarks/"
    features: "data/features/"
    labeled_features: "data/labeled_features/"
    processed_videos:
      basic: "data/processed_videos/basic/"
      annotated: "data/processed_videos/annotated/"
    metadata:
      default: "data/metadata/"
      test_data: "tests_data_pilot_for_features.csv"  # Path to test data file relative to project root
      video_segments:
        id_field: "Filename"         # Maps to "video_id" internally
        movement_field: "Movement"   # Additional metadata
        view_field: "View_Angle"     # Additional metadata
        view_angle_options: # Valid values for View_Angle
          - "front"
          - "sag_left"
          - "sag_right"
        start_frame_fields: # Multiple possible start frames
          - "rep1_start"
          - "rep2_start"
          - "rep3_start"
          - "rep4_start"
        end_frame_fields: # Multiple possible end frames
          - "rep1_end"
          - "rep2_end"
          - "rep3_end"
          - "rep4_end"

# Pose estimation settings
pose_estimation:
  algorithm: "mediapipe"  # Default pose estimator
  mediapipe:
    model_complexity: 2  # 0, 1, or 2
    min_detection_confidence: 0.5
    min_tracking_confidence: 0.5
    static_image_mode: false

# Feature extraction settings
feature_extraction:
  default_movement: "squat"
  preprocess:
    smoothing: true
    smoothing_window: 5
    interpolate_missing: true

# ML model settings
ml_model:
  algorithm: "random_forest"
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
    class_weight:
      1: 2.0  # "poor" class (higher weight)
      2: 1.0  # "moderate" class
      3: 0.5  # "good" class
    #class_weight: "balanced"  # Adds weights inversely proportional to class frequencies. Use Null for equal weights
    min_samples_split: 2
    min_samples_leaf: 1
    bootstrap: true
    oob_score: true  # Out-of-bag score estimation (useful validation metric)

# Training and validation settings
data_splitting:
  validation_set:
    enabled: true
    test_size: 0.30       # 30% held out for validation
    stratify: true        # Maintain class distribution
    random_state: 42      # For reproducibility

  cross_validation:
    enabled: true         # Can be disabled if not needed
    method: "stratified_kfold"
    n_splits: 5
    shuffle: true
    random_state: 42

# Model selection and hyperparameter tuning
model_selection:
  strategy: "cross_val"   # Options: "cross_val", "validation_set", "both"
  scoring: "f1_weighted"  # Primary metric for selection
  secondary_scoring: ["balanced_accuracy", "precision_weighted", "recall_weighted"]
  scoring_metrics_available:
    - "accuracy"
    - "precision_weighted"
    - "recall_weighted"
    - "f1_weighted"
    - "balanced_accuracy"
    - "roc_auc_ovr_weighted"
  refit: true             # Refit on all training data after selection

# Evaluation settings
evaluation:
  final_validation: true  # Evaluate on held-out validation set
  metrics: ["accuracy", "precision", "recall", "f1", "roc_auc", "confusion_matrix"]
  threshold_metrics: true
  curve_plots: ["roc", "precision_recall"]
  feature_importance: true
  save_results: true
  results_path: "results/"

# Processing settings
processing:
  n_jobs: -1  # Use all available cores
  verbose: 1


# Logging settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  save_to_file: true
  log_file: "logs/movement_analysis.log"